---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: vhj
  label: hkm
  match: "**/*"
  read_only: false
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
  publish_command: gatsby build
  output_directory: public
  preview_command: gatsby build
